collection_item: 4
time_zone: "Asia/Ho_Chi_Minh"
show_more: 1
course:
  item: 6
  min_price: 0
  min_percent_sale: 0
  max_percent_sale: 100
api:
  client_name: "client"
  company: "framgia"
  time_reset_token: 7
per_page: 5
